### PR TITLE
Add 'friz' animation control library

### PR DESCRIPTION
**Pull request by bgporter**
Add your code! To get it merged quickly, double check:

* [] You provided the full url, ala `https://github.com/myname/myrepo`
* [] No trailing slash on the end of the url
* [] The description is short n' sweet
* [] There's no period on the end of the description
* [] You didn't add extra newlines

You can add a gitlab or other url, but only github repositories currently show stars and licenses.

### CODE REVIEW

**Comment by sudara** [comment]
This is great! Could you do me a favor and add the site and description to `sites.rb` and not the README (which is autogenerated each night). I'll make it clearer in the pull request template!

**Comment by bgporter** [comment]
done, and re-committed to the PR branch.

**Comment by sudara** [comment]
Added! I cherry-picked your last commit into main to avoid the merge commits. Thanks Brett!

**Comment by sudara** [comment]
@bgporter BTW, I'm very excited about trying out your library! I had started an animation class on my own, also with all the easings from easings.net — somehow didn't manage to run into yours! I've been daydreaming about what a JUCE rendering system would look like if animation, shadows, padding, etc were all first class citizens.

**Pull request closed without merging**
